=== BilderHerunterlader/BilderUploader/hosts/hoster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Root Element -->
	<xs:element name="hoster">
		<xs:complexType>
			<xs:sequence>
				<!-- Optional Hoster Display Name -->
				<xs:element name="displayName" type="xs:string" minOccurs="0" maxOccurs="1" />
				<!-- Optional Hoster Icon Filename -->
				<xs:element name="displayIcon" type="xs:string" minOccurs="0" maxOccurs="1" />
				<!-- Optional Hoster Homepage -->
				<xs:element name="homePage" type="xs:string" minOccurs="0" maxOccurs="1" />
				
				<!-- Optional Max File Size -->
				<xs:element name="maxFileSize" type="xs:long" minOccurs="0" maxOccurs="1" />
				<!-- Optinal File Name Filter (Regex) -->
				<xs:element name="fileNameFilter" type="xs:string" minOccurs="0" maxOccurs="1" />
				
				<!-- Optional Max Connections -->
				<xs:element name="maxConnections" type="xs:int" minOccurs="0" maxOccurs="1" />
				<!-- Optional Delay in milliseconds -->
				<xs:element name="delay" type="xs:int" minOccurs="0" maxOccurs="1" />
				
				<!-- Optional Steps to generate randoms -->
				<xs:element ref="generateRandom" minOccurs="0" maxOccurs="unbounded" />
				
				<!-- Optional Steps to prepare the Upload (e.g. Login, Extract parameters for Upload) -->
				<xs:element ref="prepareUploadStep" minOccurs="0" maxOccurs="unbounded" />
				
				<!-- Required Upload Step -->
				<xs:element ref="uploadStep" />
				
				<!-- TODO Prepare Result -->
				
				<!-- Required Upload Result Step -->
				<xs:element ref="uploadResultStep" />
				
				<!-- Password Variables -->
				<xs:element name="passwordVariable" type="PasswordVariable" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<!-- Required Hoster Name -->
			<xs:attribute name="name" type="xs:string" use="required" />
			<!-- Required Hoster Version -->
			<xs:attribute name="version" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- Random Generator -->
	<xs:element name="generateRandom">
		<xs:complexType>
			<xs:sequence>
				<!-- Required Class Name -->
				<xs:element name="className" type="xs:string" />
				<xs:element ref="param" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="variableName" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Random Generator Parameter -->
	<xs:element name="param">
		<xs:complexType>
			<!-- Required Key -->
			<xs:attribute name="key" type="xs:string" use="required" />
			<!-- Required Value -->
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- Prepare Upload -->
	<xs:element name="prepareUploadStep">
		<xs:complexType>
			<xs:sequence>
				<!-- Required URL -->
				<xs:element name="url" type="xs:string" />
				<!-- Optional HTTP Method (Default is GET) -->
				<xs:element name="httpMethod" type="HTTPMethod" minOccurs="0" maxOccurs="1" />
				<!-- Optional Form Content Type (Only used when HTTP Method is POST, Default is application/x-www-form-urlencoded) -->
				<xs:element name="formContentType" type="FormContentType" minOccurs="0" maxOccurs="1" />
				<!-- Optional Additional Fields (Only used when HTTP Method is POST) -->
				<xs:element ref="additionalField" minOccurs="0" maxOccurs="unbounded" />
				<!-- Optianol Failure Regular Expressions, which will treat the upload as Failure if the Pattern is found -->
				<xs:element name="failureRegex" type="Regex" minOccurs="0" maxOccurs="unbounded" />
				<!-- Optional Regular Expressions which are used on HTTP Response Content -->
				<xs:element name="regex" type="RegexAndVariableStore" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Upload -->
	<xs:element name="uploadStep">
		<xs:complexType>
			<xs:sequence>
				<!-- Required URL -->
				<xs:element name="url" type="xs:string" />
				<!-- Required Field Name (For the file to be uploaded) -->
				<xs:element name="fieldName" type="xs:string" />
				<!-- Optional Additional Fields -->
				<xs:element ref="additionalField" minOccurs="0" maxOccurs="unbounded" />
				<!-- Optianol Failure Regular Expressions, which will treat the upload as Failure if the Pattern is found -->
				<xs:element name="failureRegex" type="Regex" minOccurs="0" maxOccurs="unbounded" />
				<!-- Optional Regular Expressions which can be used to change the filename, because some hosts may not accept certain characters or too long filenames -->
				<xs:element name="filenameRegex" type="RegexAndReplacement" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Upload Additional Field -->
	<xs:element name="additionalField">
		<xs:complexType>
			<!-- Required Field Name -->
			<xs:attribute name="fieldName" type="xs:string" use="required" />
			<!-- Required Field Value -->
			<xs:attribute name="fieldValue" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- Upload Result -->
	<xs:element name="uploadResultStep">
		<xs:complexType>
			<xs:sequence>
				<!-- Optional Regular Expressions which are used on HTTP Response Content -->
				<xs:element name="regex" type="RegexAndReplacement" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Regex -->
	<xs:complexType name="Regex">
		<xs:sequence>
			<!-- Required Regex Pattern -->
			<xs:element name="pattern" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- Regex and Replacement -->
	<xs:complexType name="RegexAndReplacement">
		<xs:complexContent>
			<xs:extension base="Regex">
				<xs:sequence>
					<!-- Required replacement -->
					<xs:element name="replacement" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- Regex with Replacements -->
	<xs:complexType name="RegexAndVariableStore">
		<xs:complexContent>
			<xs:extension base="Regex">
				<xs:sequence>
					<!-- Optional replacement -->
					<xs:element name="replacement" type="xs:string" minOccurs="0" maxOccurs="1" />
					<!-- Optional replacement variables stored to variables using replaceAll method -->
					<xs:element name="replacementVariable" type="RegexReplacementVariableStore" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- Regex Replacement -->
	<xs:complexType name="RegexReplacementVariableStore">
		<!-- Required Variable name to store the replacement -->
		<xs:attribute name="variableName" type="xs:string" use="required" />
		<!-- Required Replacement-->
		<xs:attribute name="replacement" type="xs:string" use="required" />
	</xs:complexType>
	
	<!-- HTTP Method -->
	<xs:simpleType name="HTTPMethod">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GET" />
			<xs:enumeration value="POST" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Form Content Type -->
	<xs:simpleType name="FormContentType">
		<xs:restriction base="xs:string">
			<!-- multipart/form-data -->
			<xs:enumeration value="MultiPartFormData" />
			<!-- application/x-www-form-urlencoded -->
			<xs:enumeration value="XWWWFormURLEncoded" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Password Variable -->
	<xs:complexType name="PasswordVariable">
		<!-- Required Variable name -->
		<xs:attribute name="variableName" type="xs:string" use="required" />
		<!-- Required Flag if value should be encrypted -->
		<xs:attribute name="encrypted" type="xs:boolean" />
	</xs:complexType>
</xs:schema>

=== BilderHerunterlader/BilderUploader/hosts/ImageVenue-Family.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hoster name="ImageVenue-Family" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com hoster.xsd">
	<displayName>ImageVenue (Family safe)</displayName>
	<displayIcon>imagevenue.ico</displayIcon>
	<homePage>http://www.imagevenue.com</homePage>

	<maxFileSize>6000000</maxFileSize>
	<fileNameFilter>(?i)\.(?:jpg|jpeg)$</fileNameFilter>

	<uploadStep>
		<url>http://www.imagevenue.com/upload.php</url>
		<fieldName>userfile[]</fieldName>
		<additionalField fieldName="imgcontent" fieldValue="safe" />
		<additionalField fieldName="MAX_FILE_SIZE" fieldValue="" />
		<additionalField fieldName="action" fieldValue="1" />
		<additionalField fieldName="img_resize" fieldValue="" />
		<additionalField fieldName="submit" fieldValue="Go" />
	</uploadStep>
	
	<uploadResultStep>
		<regex>
			<pattern>(?ism)(\[URL=[^\]]+\]\[IMG\][^\[]+\[/IMG\]\[/URL\])</pattern>
			<replacement>$1</replacement>
		</regex>
	</uploadResultStep>
</hoster>

=== BilderHerunterlader/BilderUploader/hosts/ImageBam-Family.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hoster name="ImageBam-Family" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com hoster.xsd">
	<displayName>ImageBam (Family safe)</displayName>
	<displayIcon>imagebam.ico</displayIcon>
	<homePage>http://www.imagebam.com</homePage>

	<maxFileSize>10485760</maxFileSize>
	<fileNameFilter>(?i)\.(?:jpg|jpeg|png|gif)$</fileNameFilter>
	
	<maxConnections>6</maxConnections>

	<uploadStep>
		<url>http://www.imagebam.com/sys/upload/save</url>
		<fieldName>file[]</fieldName>
		<additionalField fieldName="content_type" fieldValue="0" />
		<additionalField fieldName="thumb_size" fieldValue="180" />
		<additionalField fieldName="thumb_aspect_ratio" fieldValue="resize" />
		<additionalField fieldName="thumb_file_type" fieldValue="jpg" />
		<additionalField fieldName="thumb_info" fieldValue="0" />
		<additionalField fieldName="gallery_options" fieldValue="0" />
		<failureRegex>
			<pattern>(?s)&lt;h1&gt;An Error Was Encountered&lt;/h1&gt;.+?&lt;p&gt;Error.+?&lt;/p&gt;.+?&lt;/div&gt;</pattern>
		</failureRegex>
		<filenameRegex>
			<pattern>^(.{0,95}).+?(\.[^.]+)?$</pattern>
			<replacement>$1$2</replacement>
		</filenameRegex>
	</uploadStep>
	
	<uploadResultStep>
		<regex>
			<pattern>(?ism)&lt;textarea onClick=&quot;this\.select\(\);&quot;.+?&gt;(\[URL=http://www\.imagebam\.com/image/[^\]]+\]\[IMG\]http://[^\[]+\[/IMG\]\[/URL\])</pattern>
			<replacement>$1</replacement>
		</regex>
	</uploadResultStep>
</hoster>

=== BilderHerunterlader/BilderUploader/hosts/Zippyshare.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hoster name="Zippyshare" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com hoster.xsd">
	<displayName>Zippyshare</displayName>
	<displayIcon>zippyshare.ico</displayIcon>
	<homePage>https://www.zippyshare.com</homePage>

	<maxConnections>1</maxConnections>

	<prepareUploadStep>
		<url>https://www.zippyshare.com/</url>
		<regex>
			<pattern>&lt;form method=&quot;post&quot;.+?id=&quot;upload_form&quot;.+?action=&quot;https?://(.+?)&quot;&gt;</pattern>
			<replacementVariable variableName="UploadURL" replacement="$1" />
		</regex>
	</prepareUploadStep>

	<uploadStep>
		<url>https://${UploadURL}</url>
		<fieldName>file</fieldName>
		<additionalField fieldName="name" fieldValue="${FileName}" />
		<additionalField fieldName="notprivate" fieldValue="true" />
		<additionalField fieldName="zipname" fieldValue="" />
		<additionalField fieldName="ziphash" fieldValue="" />
		<additionalField fieldName="embPlayerValues" fieldValue="false" />
	</uploadStep>
	
	<uploadResultStep>
		<regex>
			<pattern>(?s)&lt;strong&gt;Link:&lt;/strong&gt;.+?&lt;input.+?value=&quot;(https?://.+?\.zippyshare.com.+?)&quot;</pattern>
			<replacement>[URL]$1[/URL]</replacement>
		</regex>
	</uploadResultStep>
</hoster>

=== BilderHerunterlader/BilderUploader/hosts/ImageVenue-Adult.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hoster name="ImageVenue-Adult" version="0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com hoster.xsd">
	<displayName>ImageVenue (Adult)</displayName>
	<displayIcon>imagevenue.ico</displayIcon>
	<homePage>http://www.imagevenue.com</homePage>

	<maxFileSize>6000000</maxFileSize>
	<fileNameFilter>(?i)\.(?:jpg|jpeg)$</fileNameFilter>

	<maxConnections>5</maxConnections>

	<prepareUploadStep>
		<url>http://www.imagevenue.com/</url>
		<regex>
			<pattern>&lt;meta name=&quot;csrf-token&quot; content=&quot;(.+?)&quot;</pattern>
			<replacementVariable variableName="CSRFToken" replacement="$1" />
		</regex>
	</prepareUploadStep>

	<prepareUploadStep>
		<url>http://www.imagevenue.com/upload/session</url>
		<httpMethod>POST</httpMethod>
		<additionalField fieldName="thumbnail_size" fieldValue="2" />
		<additionalField fieldName="content_type" fieldValue="nsfw" />
		<additionalField fieldName="comments_enabled" fieldValue="false" />
		<additionalHeader headerName="X-CSRF-TOKEN" headerValue="${CSRFToken}" />
		<regex>
			<pattern>&quot;data&quot;:&quot;(.+?)&quot;</pattern>
			<replacementVariable variableName="UploadData" replacement="$1" />
		</regex>
		<regex>
			<pattern>&quot;session&quot;:&quot;(.+?)&quot;</pattern>
			<replacementVariable variableName="UploadSessionID" replacement="$1" />
		</regex>
	</prepareUploadStep>

	<uploadStep>
		<url>http://www.imagevenue.com/upload</url>
		<fieldName>files[0]</fieldName>
		<additionalField fieldName="data" fieldValue="${UploadData}" />
		<additionalField fieldName="_token" fieldValue="${CSRFToken}" />
		<failureRegex>
			<pattern>There was an error uploading the files</pattern>
		</failureRegex>
	</uploadStep>
	
	<prepareResultStep>
		<url>http://www.imagevenue.com/upload/complete?session=${UploadSessionID}</url>
	</prepareResultStep>
	
	<uploadResultStep>
		<regex>
			<pattern>(?ism)(\[URL=[^\]]+\]\[IMG\][^\[]+\[/IMG\]\[/URL\])</pattern>
			<replacement>$1</replacement>
		</regex>
	</uploadResultStep>
</hoster>

=== BilderHerunterlader/BilderUploader/hosts/Uploaded.net-HTTPS.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hoster name="Uploaded-HTTPS" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.w3schools.com hoster.xsd">
	<displayName>Uploaded.net (HTTPS)</displayName>
	<displayIcon>uploaded.net.ico</displayIcon>
	<homePage>https://uploaded.net/</homePage>

	<maxConnections>1</maxConnections>

	<generateRandom>
		<className>UploadedNetRandomGenerator</className>
		<param key="len" value="6" />
		<variableName>AdminCode</variableName>
	</generateRandom>

	<prepareUploadStep>
		<url>https://uploaded.net/io/login</url>
		<httpMethod>POST</httpMethod>
		<additionalField fieldName="id" fieldValue="${Username}" />
		<additionalField fieldName="pw" fieldValue="${Password}" />
	</prepareUploadStep>
	
	<prepareUploadStep>
		<url>https://uploaded.net/</url>
		<regex>
			<pattern>&lt;input type=&quot;hidden&quot; id=&quot;user_id&quot; value=&quot;(.+?)&quot;</pattern>
			<replacementVariable variableName="UserID" replacement="$1" />
		</regex>
		<regex>
			<pattern>&lt;input type=&quot;hidden&quot; id=&quot;user_pw&quot; value=&quot;(.+?)&quot;</pattern>
			<replacementVariable variableName="UserPW" replacement="$1" />
		</regex>
	</prepareUploadStep>
	
	<prepareUploadStep>
		<url>https://uploaded.net/js/script.js</url>
		<regex>
			<pattern>uploadServer = &apos;(.+?)&apos;</pattern>
			<replacementVariable variableName="UploadServer" replacement="$1" />
		</regex>
	</prepareUploadStep>

	<uploadStep>
		<url>${UploadServer}upload?admincode=${AdminCode}&amp;id=${UserID}&amp;pw=${UserPW}</url>
		<fieldName>Filedata</fieldName>
		<additionalField fieldName="Filename" fieldValue="${FileName}" />
	</uploadStep>
	
	<uploadResultStep>
		<regex>
			<pattern>([^,]+),</pattern>
			<replacement>[URL]https://uploaded.net/file/$1[/URL]</replacement>
		</regex>
	</uploadResultStep>
	
	<passwordVariable variableName="Username" />
	<passwordVariable variableName="Password" encrypted="true" />
</hoster>
